function myhelp() {
  echo ""
  echo "========================================="
  echo "        🚀 MY SHORTCUTS & PLUGINS"
  echo "========================================="
  echo ""
  echo "🖥️  TERMINATOR"
  echo "  Ctrl+Shift+O       → Split horizontal"
  echo "  Ctrl+Shift+E       → Split vertical"
  echo "  Alt+Arrow           → Navigate between panels"
  echo "  Ctrl+Shift+W       → Close current panel"
  echo "  Ctrl+Shift+T       → New tab"
  echo ""
  echo "📂 Z"
  echo "  z <folder>          → Jump to folder (ex: z proj)"
  echo ""
  echo "📎 COPYPATH"
  echo "  copypath             → Copy current folder path"
  echo ""
  echo "📄 JSONTOOLS"
  echo "  cat file | pp_json   → Format JSON pretty"
  echo "  cat file | is_json   → Check if valid JSON"
  echo ""
  echo "🐳 DOCKER COMPOSE"
  echo "  dco    dcb    dce    dcps"
  echo "  dcup   dcupb  dcupd  dcupdb"
  echo "  dcdn   dcl    dclf"
  echo "  dcstart  dcstop  dcrestart"
  echo "  dcr    dcrm   dcpull  dck"
  echo ""
  echo "🐍 PYTHON"
  echo "  py       pyfind    pyclean"
  echo "  pygrep   pyserver  mkv    vrun"
  echo ""
  echo "📦 PIP"
  echo "  pipi    pipu    pipun"
  echo "  pipgi   piplo   pipreq   pipir"
  echo ""
  echo "⚡ UV"
  echo "  uv init                            → create new project"
  echo "  uv add <pkg>                       → add dependency"
  echo "  uv remove <pkg>                    → remove dependency"
  echo "  uv sync                            → install all dependencies"
  echo "  uv run <script.py>                 → run with managed env"
  echo "  uv venv                            → create venv"
  echo "  uv pip install <pkg>               → pip compatible install"
  echo "  uv pip compile requirements.in     → lock dependencies"
  echo "  uv python install 3.12             → install python version"
  echo "  uv python list                     → list available versions"
  echo ""
  echo "🔍 EZA"
  echo "  ezalt                              → tree level 2 + git + dirs first"
  echo "  eza -la --icons --git              → list all + icons + git status"
  echo "  eza --tree --level=3               → tree 3 levels"
  echo "  eza --tree --level=2 --icons       → tree 2 levels + icons"
  echo "  eza -l --sort=size                 → sort by size"
  echo "  eza -l --sort=modified             → sort by date"
  echo "  eza -l --sort=ext                  → sort by extension"
  echo "  eza --git-ignore --tree            → tree respecting .gitignore"
  echo "  eza -la --group-directories-first  → dirs first + all files"
  echo ""
  echo "🧹 RUFF"
  echo "  ruff check .                       → lint project"
  echo "  ruff check . --fix                 → lint + auto fix"
  echo "  ruff format .                      → format project"
  echo "  ruff format --check .              → check format without changing"
  echo ""
  echo "🔬 PY-SPY"
  echo "  sudo py-spy top --pid <PID>        → monitor live"
  echo "  sudo py-spy record -o out.svg --pid <PID> → flamegraph"
  echo "  py-spy top -- python script.py     → profile from start"
  echo ""
  echo "🔗 PRE-COMMIT"
  echo "  pre-commit install                 → activate in project"
  echo "  pre-commit run --all-files         → run on all files"
  echo "  git commit --no-verify             → skip pre-commit"
  echo ""
  echo "🐋 DOCKER SERVICES"
  echo "  Redis      → localhost:6379"
  echo "  SonarQube  → localhost:9000  (admin/admin)"
  echo "  MLflow     → localhost:5000"
  echo "  Prefect    → localhost:4200"
  echo ""
  echo "🔒 HADOLINT"
  echo "  hadolint Dockerfile                → lint Dockerfile"
  echo "  hadolint --ignore DL3008 Dockerfile → ignore specific rule"
  echo ""
  echo "🛡️  TRIVY"
  echo "  trivy fs .                         → scan project files"
  echo "  trivy image <image>                → scan docker image"
  echo "  trivy fs --severity HIGH,CRITICAL . → scan only high/critical"
  echo ""
  echo "🚀 ALBERT"
  echo "  Alt+Space                          → open launcher"
  echo ""
  echo "📸 FLAMESHOT"
  echo "  flameshot gui                      → screenshot with annotations"
  echo ""
  echo "🎨 zsh-autosuggestions"
  echo "💡 you-should-use"
  echo "❓ command-not-found"
  echo ""
  echo "========================================="
}

# Aliases
alias ezalt="eza --git --group-directories-first --tree --level=2"
